name: Coding Time Statistics
on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: "0 */2 * * *"  # Runs every 2 hours
  push:
    branches: [ main, master ]  # Update on pushes to main branches
    
jobs:
  update-readme:
    name: "📊 Update Coding Statistics"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "⚡ Generate WakaTime Stats"
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TIME_RANGE: year
          START_YEAR: 2024
          SHOW_TITLE: true
          SHOW_TIME: true
          SHOW_TOTAL: true
          BLOCKS: ⚪⚫🔵🔴🟣🟡  # More distinctive blocks
          COMMIT_MESSAGE: "📊 Updated coding activity graph"
          # Customized section formatting
          SECTION_NAME: "📈 Weekly Coding Stats"
          SHOW_LANGUAGE: true
          SHOW_DAYS_OF_WEEK: true
          SHOW_PROJECTS: true
          SHOW_TIMEZONE: true
          SHOW_EDITORS: true
          SHOW_OS: true
          SYMBOL_VERSION: 2
