name: Waka Readme

on:
  schedule:
    - cron: '0 0 * * *' # Runs at 00:00 UTC everyday
  workflow_dispatch: # Allows manual workflow trigger
  
jobs:
  update-readme:
    name: WakaTime Readme Stats
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPOSITORY: amaralkaff/amaralkaff # your GitHub username and repository
          SHOW_TITLE: true
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          TIME_RANGE: last_7_days
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
