name: Coding Time Statistics
on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: "0 */2 * * *"  # Runs every 2 hours
  push:
    branches: [ main, master ]  # Update on pushes to main branches
    
jobs:
  update-readme:
    name: "📊 Update Coding Statistics"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "⚡ Generate WakaTime Stats"
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TITLE: true
          SECTION_NAME: "waka"
          BLOCKS: 🌑🌒🌓🌔🌕🌝  # Moon phases for a space theme
          TIME_RANGE: "last_7_days"
          LANG_COUNT: 10
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: false
          STOP_AT_OTHER: true
          COMMIT_MESSAGE: "📊 Updated coding activity graph"
